try{


	//add code within a try catch method just make sure that catch is written as it is below


	console.log('nice');
	console.log(1);
	v
	console.log(3);





}
catch(e){
	console.log('erRoR'+e);
}